=begin
#Microsoft Bot Connector API - v3.0

#The Bot Connector REST API allows your bot to send and receive messages to channels configured in the  [Bot Framework Developer Portal](https://dev.botframework.com). The Connector service uses industry-standard REST  and JSON over HTTPS.    Client libraries for this REST API are available. See below for a list.    Many bots will use both the Bot Connector REST API and the associated [Bot State REST API](/en-us/restapi/state). The  Bot State REST API allows a bot to store and retrieve state associated with users and conversations.    Authentication for both the Bot Connector and Bot State REST APIs is accomplished with JWT Bearer tokens, and is  described in detail in the [Connector Authentication](/en-us/restapi/authentication) document.    # Client Libraries for the Bot Connector REST API    * [Bot Builder for C#](/en-us/csharp/builder/sdkreference/)  * [Bot Builder for Node.js](/en-us/node/builder/overview/)  * Generate your own from the [Connector API Swagger file](https://raw.githubusercontent.com/Microsoft/BotBuilder/master/CSharp/Library/Microsoft.Bot.Connector.Shared/Swagger/ConnectorAPI.json)    © 2016 Microsoft

OpenAPI spec version: v3
Contact: botframework@microsoft.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.29
=end

require 'spec_helper'
require 'json'

# Unit tests for BotFramework::ConversationsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ConversationsApi' do
  before do
    # run before each test
    @instance = BotFramework::ConversationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ConversationsApi' do
    it 'should create an instance of ConversationsApi' do
      expect(@instance).to be_instance_of(BotFramework::ConversationsApi)
    end
  end

  # unit tests for conversations_create_conversation
  # CreateConversation
  # Create a new Conversation.    POST to this method with a  * Bot being the bot creating the conversation  * IsGroup set to true if this is not a direct message (default is false)  * Array containing the members to include in the conversation    The return value is a ResourceResponse which contains a conversation id which is suitable for use  in the message payload and REST API uris.    Most channels only support the semantics of bots initiating a direct message conversation.  An example of how to do that would be:    &#x60;&#x60;&#x60;  var resource &#x3D; await connector.conversations.CreateConversation(new ConversationParameters(){ Bot &#x3D; bot, members &#x3D; new ChannelAccount[] { new ChannelAccount(\&quot;user1\&quot;) } );  await connect.Conversations.SendToConversationAsync(resource.Id, new Activity() ... ) ;    &#x60;&#x60;&#x60;
  # @param body Parameters to create the conversation from
  # @param [Hash] opts the optional parameters
  # @return [ConversationResourceResponse]
  describe 'conversations_create_conversation test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for conversations_create_conversation
  # CreateConversation
  # Create a new Conversation.    POST to this method with a  * Bot being the bot creating the conversation  * IsGroup set to true if this is not a direct message (default is false)  * Array containing the members to include in the conversation    The return value is a ResourceResponse which contains a conversation id which is suitable for use  in the message payload and REST API uris.    Most channels only support the semantics of bots initiating a direct message conversation.  An example of how to do that would be:    &#x60;&#x60;&#x60;  var resource &#x3D; await connector.conversations.CreateConversation(new ConversationParameters(){ Bot &#x3D; bot, members &#x3D; new ChannelAccount[] { new ChannelAccount(\&quot;user1\&quot;) } );  await connect.Conversations.SendToConversationAsync(resource.Id, new Activity() ... ) ;    &#x60;&#x60;&#x60;
  # @param is_group 
  # @param bot 
  # @param members 
  # @param topic_name 
  # @param tenant_id 
  # @param activity 
  # @param channel_data 
  # @param [Hash] opts the optional parameters
  # @return [ConversationResourceResponse]
  describe 'conversations_create_conversation test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for conversations_delete_activity
  # DeleteActivity
  # Delete an existing activity.    Some channels allow you to delete an existing activity, and if successful this method will remove the specified activity.
  # @param conversation_id Conversation ID
  # @param activity_id activityId to delete
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'conversations_delete_activity test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for conversations_delete_conversation_member
  # DeleteConversationMember
  # Deletes a member from a conversation.     This REST API takes a ConversationId and a memberId (of type string) and removes that member from the conversation. If that member was the last member  of the conversation, the conversation will also be deleted.
  # @param conversation_id Conversation ID
  # @param member_id ID of the member to delete from this conversation
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'conversations_delete_conversation_member test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for conversations_get_activity_members
  # GetActivityMembers
  # Enumerate the members of an activity.     This REST API takes a ConversationId and a ActivityId, returning an array of ChannelAccount objects representing the members of the particular activity in the conversation.
  # @param conversation_id Conversation ID
  # @param activity_id Activity ID
  # @param [Hash] opts the optional parameters
  # @return [Array<ChannelAccount>]
  describe 'conversations_get_activity_members test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for conversations_get_conversation_members
  # GetConversationMembers
  # Enumerate the members of a conversation.     This REST API takes a ConversationId and returns an array of ChannelAccount objects representing the members of the conversation.
  # @param conversation_id Conversation ID
  # @param [Hash] opts the optional parameters
  # @return [Array<ChannelAccount>]
  describe 'conversations_get_conversation_members test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for conversations_get_conversation_paged_members
  # GetConversationPagedMembers
  # Enumerate the members of a conversation one page at a time.    This REST API takes a ConversationId. Optionally a pageSize and/or continuationToken can be provided. It returns a PagedMembersResult, which contains an array  of ChannelAccounts representing the members of the conversation and a continuation token that can be used to get more values.    One page of ChannelAccounts records are returned with each call. The number of records in a page may vary between channels and calls. The pageSize parameter can be used as   a suggestion. If there are no additional results the response will not contain a continuation token. If there are no members in the conversation the Members will be empty or not present in the response.    A response to a request that has a continuation token from a prior request may rarely return members from a previous request.
  # @param conversation_id Conversation ID
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page_size Suggested page size
  # @option opts [String] :continuation_token Continuation Token
  # @return [PagedMembersResult]
  describe 'conversations_get_conversation_paged_members test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for conversations_get_conversations
  # GetConversations
  # List the Conversations in which this bot has participated.    GET from this method with a skip token    The return value is a ConversationsResult, which contains an array of ConversationMembers and a skip token.  If the skip token is not empty, then   there are further values to be returned. Call this method again with the returned token to get more values.    Each ConversationMembers object contains the ID of the conversation and an array of ChannelAccounts that describe the members of the conversation.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :continuation_token skip or continuation token
  # @return [ConversationsResult]
  describe 'conversations_get_conversations test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for conversations_reply_to_activity
  # ReplyToActivity
  # This method allows you to reply to an activity.    This is slightly different from SendToConversation().  * SendToConversation(conversationId) - will append the activity to the end of the conversation according to the timestamp or semantics of the channel.  * ReplyToActivity(conversationId,ActivityId) - adds the activity as a reply to another activity, if the channel supports it. If the channel does not support nested replies, ReplyToActivity falls back to SendToConversation.    Use ReplyToActivity when replying to a specific activity in the conversation.    Use SendToConversation in all other cases.
  # @param body Activity to send
  # @param conversation_id Conversation ID
  # @param activity_id activityId the reply is to (OPTIONAL)
  # @param [Hash] opts the optional parameters
  # @return [ResourceResponse]
  describe 'conversations_reply_to_activity test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for conversations_reply_to_activity
  # ReplyToActivity
  # This method allows you to reply to an activity.    This is slightly different from SendToConversation().  * SendToConversation(conversationId) - will append the activity to the end of the conversation according to the timestamp or semantics of the channel.  * ReplyToActivity(conversationId,ActivityId) - adds the activity as a reply to another activity, if the channel supports it. If the channel does not support nested replies, ReplyToActivity falls back to SendToConversation.    Use ReplyToActivity when replying to a specific activity in the conversation.    Use SendToConversation in all other cases.
  # @param type 
  # @param id 
  # @param timestamp 
  # @param local_timestamp 
  # @param local_timezone 
  # @param caller_id 
  # @param service_url 
  # @param channel_id 
  # @param from 
  # @param conversation 
  # @param recipient 
  # @param text_format 
  # @param attachment_layout 
  # @param members_added 
  # @param members_removed 
  # @param reactions_added 
  # @param reactions_removed 
  # @param topic_name 
  # @param history_disclosed 
  # @param locale 
  # @param text 
  # @param speak 
  # @param input_hint 
  # @param summary 
  # @param suggested_actions 
  # @param attachments 
  # @param entities 
  # @param channel_data 
  # @param action 
  # @param reply_to_id 
  # @param label 
  # @param value_type 
  # @param value 
  # @param name 
  # @param relates_to 
  # @param code 
  # @param expiration 
  # @param importance 
  # @param delivery_mode 
  # @param listen_for 
  # @param text_highlights 
  # @param semantic_action 
  # @param conversation_id Conversation ID
  # @param activity_id activityId the reply is to (OPTIONAL)
  # @param [Hash] opts the optional parameters
  # @return [ResourceResponse]
  describe 'conversations_reply_to_activity test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for conversations_send_conversation_history
  # SendConversationHistory
  # This method allows you to upload the historic activities to the conversation.    Sender must ensure that the historic activities have unique ids and appropriate timestamps. The ids are used by the client to deal with duplicate activities and the timestamps are used by the client to render the activities in the right order.
  # @param body Historic activities
  # @param conversation_id Conversation ID
  # @param [Hash] opts the optional parameters
  # @return [ResourceResponse]
  describe 'conversations_send_conversation_history test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for conversations_send_conversation_history
  # SendConversationHistory
  # This method allows you to upload the historic activities to the conversation.    Sender must ensure that the historic activities have unique ids and appropriate timestamps. The ids are used by the client to deal with duplicate activities and the timestamps are used by the client to render the activities in the right order.
  # @param activities 
  # @param conversation_id Conversation ID
  # @param [Hash] opts the optional parameters
  # @return [ResourceResponse]
  describe 'conversations_send_conversation_history test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for conversations_send_to_conversation
  # SendToConversation
  # This method allows you to send an activity to the end of a conversation.    This is slightly different from ReplyToActivity().  * SendToConversation(conversationId) - will append the activity to the end of the conversation according to the timestamp or semantics of the channel.  * ReplyToActivity(conversationId,ActivityId) - adds the activity as a reply to another activity, if the channel supports it. If the channel does not support nested replies, ReplyToActivity falls back to SendToConversation.    Use ReplyToActivity when replying to a specific activity in the conversation.    Use SendToConversation in all other cases.
  # @param body Activity to send
  # @param conversation_id Conversation ID
  # @param [Hash] opts the optional parameters
  # @return [ResourceResponse]
  describe 'conversations_send_to_conversation test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for conversations_send_to_conversation
  # SendToConversation
  # This method allows you to send an activity to the end of a conversation.    This is slightly different from ReplyToActivity().  * SendToConversation(conversationId) - will append the activity to the end of the conversation according to the timestamp or semantics of the channel.  * ReplyToActivity(conversationId,ActivityId) - adds the activity as a reply to another activity, if the channel supports it. If the channel does not support nested replies, ReplyToActivity falls back to SendToConversation.    Use ReplyToActivity when replying to a specific activity in the conversation.    Use SendToConversation in all other cases.
  # @param type 
  # @param id 
  # @param timestamp 
  # @param local_timestamp 
  # @param local_timezone 
  # @param caller_id 
  # @param service_url 
  # @param channel_id 
  # @param from 
  # @param conversation 
  # @param recipient 
  # @param text_format 
  # @param attachment_layout 
  # @param members_added 
  # @param members_removed 
  # @param reactions_added 
  # @param reactions_removed 
  # @param topic_name 
  # @param history_disclosed 
  # @param locale 
  # @param text 
  # @param speak 
  # @param input_hint 
  # @param summary 
  # @param suggested_actions 
  # @param attachments 
  # @param entities 
  # @param channel_data 
  # @param action 
  # @param reply_to_id 
  # @param label 
  # @param value_type 
  # @param value 
  # @param name 
  # @param relates_to 
  # @param code 
  # @param expiration 
  # @param importance 
  # @param delivery_mode 
  # @param listen_for 
  # @param text_highlights 
  # @param semantic_action 
  # @param conversation_id Conversation ID
  # @param [Hash] opts the optional parameters
  # @return [ResourceResponse]
  describe 'conversations_send_to_conversation test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for conversations_update_activity
  # UpdateActivity
  # Edit an existing activity.    Some channels allow you to edit an existing activity to reflect the new state of a bot conversation.    For example, you can remove buttons after someone has clicked \&quot;Approve\&quot; button.
  # @param body replacement Activity
  # @param conversation_id Conversation ID
  # @param activity_id activityId to update
  # @param [Hash] opts the optional parameters
  # @return [ResourceResponse]
  describe 'conversations_update_activity test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for conversations_update_activity
  # UpdateActivity
  # Edit an existing activity.    Some channels allow you to edit an existing activity to reflect the new state of a bot conversation.    For example, you can remove buttons after someone has clicked \&quot;Approve\&quot; button.
  # @param type 
  # @param id 
  # @param timestamp 
  # @param local_timestamp 
  # @param local_timezone 
  # @param caller_id 
  # @param service_url 
  # @param channel_id 
  # @param from 
  # @param conversation 
  # @param recipient 
  # @param text_format 
  # @param attachment_layout 
  # @param members_added 
  # @param members_removed 
  # @param reactions_added 
  # @param reactions_removed 
  # @param topic_name 
  # @param history_disclosed 
  # @param locale 
  # @param text 
  # @param speak 
  # @param input_hint 
  # @param summary 
  # @param suggested_actions 
  # @param attachments 
  # @param entities 
  # @param channel_data 
  # @param action 
  # @param reply_to_id 
  # @param label 
  # @param value_type 
  # @param value 
  # @param name 
  # @param relates_to 
  # @param code 
  # @param expiration 
  # @param importance 
  # @param delivery_mode 
  # @param listen_for 
  # @param text_highlights 
  # @param semantic_action 
  # @param conversation_id Conversation ID
  # @param activity_id activityId to update
  # @param [Hash] opts the optional parameters
  # @return [ResourceResponse]
  describe 'conversations_update_activity test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for conversations_upload_attachment
  # UploadAttachment
  # Upload an attachment directly into a channel&#x27;s blob storage.    This is useful because it allows you to store data in a compliant store when dealing with enterprises.    The response is a ResourceResponse which contains an AttachmentId which is suitable for using with the attachments API.
  # @param body Attachment data
  # @param conversation_id Conversation ID
  # @param [Hash] opts the optional parameters
  # @return [ResourceResponse]
  describe 'conversations_upload_attachment test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for conversations_upload_attachment
  # UploadAttachment
  # Upload an attachment directly into a channel&#x27;s blob storage.    This is useful because it allows you to store data in a compliant store when dealing with enterprises.    The response is a ResourceResponse which contains an AttachmentId which is suitable for using with the attachments API.
  # @param type 
  # @param name 
  # @param original_base64 
  # @param thumbnail_base64 
  # @param conversation_id Conversation ID
  # @param [Hash] opts the optional parameters
  # @return [ResourceResponse]
  describe 'conversations_upload_attachment test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
